# Global configuration for the RL Trading System

# System paths
paths:
  data: "./data"
  models: "./models"
  logs: "./logs"

# MT5 Connection parameters
mt5:
  server: "Deriv-Demo"
  login: 40616173  # Replace with your login
  password: "Th@70366636"  # Replace with your password
  timeout: 60000  # Connection timeout in milliseconds

# General trading parameters
trading:
  symbols: ["EURUSD", "GBPUSD", "USDJPY","XAUUSD"]
  timeframes: ["M1","M5", "M15", "H1"]
  default_timeframe: "M5"
  default_symbol: "XAUUSD"
  
# Data parameters
data:
  history_days: 365  # Amount of historical data to load (days)
  feature_window: 20  # Window size for feature calculation

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "trading_system.log"